on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform:iOS Simulator, id:08182FD3-BAD7-4860-A084-9AD360278420, OS:14.2, name:iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Gems
        run: |
          gem install bundler
          bundle install
      - name: Setup pods
        run: pod install
      - name: Build and test
        run: |
          xcodebuild clean build test -workspace Movies.xcworkspace -scheme BBNetwork -enableCodeCoverage YES -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
