name: Run CI
on: push

jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@develop
        - name: Build
        run: |
        set -o pipefail
        xcodebuild build \
        -scheme BBNetwork \
        -destination 'platform=iOS Simulator, name=iPhone 11 Pro' \
        | xcpretty
