name: Swift

on:
  push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd Movies
        swift build -v
        |
    - name: Run tests
      run: | 
        cd Movies
        swift test -v
        |
